---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-template"
metadata:
  name: "${REPO_NAME}-frontend-static-bc"
  creationTimestamp:
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${REPO_NAME}-frontend-static"
    name: s2i-caddy
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker-registry.default.svc:5000/bcgov/s2i-caddy:v1-stable
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/bcgov/s2i-caddy:v1-stable
      generation:
      importPolicy: {}
      name: v1-stable
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${REPO_NAME}-frontend-static"
    name: "${REPO_NAME}-frontend-static"
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${REPO_NAME}-frontend-static"
    name: "${REPO_NAME}-frontend-static-${JOB_NAME}"
  spec:
    completionDeadlineSeconds: 600
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${REPO_NAME}-frontend-static:latest"
    postCommit: {}
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    runPolicy: SerialLatestOnly
    source:
      dockerfile: |-
        FROM docker-registry.default.svc:5000/bcgov/s2i-caddy:v1-stable
        COPY tmp/dist/ /var/www/html/
        CMD /tmp/scripts/run
      images:
      - as:
        from:
          kind: ImageStreamTag
          name: "${REPO_NAME}-frontend:${JOB_NAME}"
          namespace: k8vopl-tools
        paths:
        - destinationDir: tmp
          sourcePath: "/opt/app-root/src/dist"
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-caddy:v1-stable
      type: Docker
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: "${REPO_NAME}-frontend:${JOB_NAME}"
          namespace: k8vopl-tools
      type: ImageChange
    - type: ConfigChange
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: JOB_NAME
  description: Job identifier (i.e. 'pr-5' OR 'master')
  required: true
