---
openapi: 3.0.2
info:
  version: 1.0.0
  title: GetOK API
  description: >-
    This API automates the process for getting setup to use common services
    published on https://apistore.nrs.gov.bc.ca/store/
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: NR Common Service Showcase
    email: NR.CommonServiceShowcase@gov.bc.ca
servers:
  - url: /api/v1
    description: This Server
security:
  - bearerAuth: []
  - OpenID: []
paths:
  '/acronyms/{acronym}':
    get:
      summary: Returns the details that GETOK stores about an application acronym
      operationId: getAcronym
      tags:
        - Acronyms
      parameters:
        - name: acronym
          in: path
          description: Name of the project
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Acronym details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcronymDetail'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /checks/status:
    get:
      summary: Returns status of correspondent APIs
      operationId: checkStatus
      tags:
        - Checks
      responses:
        '200':
          description: Responds if the correspondent API endpoint(s) are healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/webAde/{webAdeEnv}/{acronym}/appConfig/':
    get:
      summary: >-
        Returns WebADE JSON response for the specified acronym in the specified
        environment
      operationId: appConfigGetAcronym
      tags:
        - Application Configuration
      parameters:
        - name: acronym
          in: path
          description: Name of the project
          required: true
          schema:
            type: string
        - name: webAdeEnv
          in: path
          description: The ISSS WebADE environment
          required: true
          schema:
            type: string
            enum:
              - INT
              - TEST
              - PROD
      responses:
        '200':
          description: WebADE JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfig'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/webAde/{webAdeEnv}/{acronym}/dependencies/':
    get:
      summary: Returns a list of other WebADE acronyms that reference the one supplied
      operationId: getDependencies
      tags:
        - Application Configuration
      parameters:
        - name: acronym
          in: path
          description: Name of the project
          required: true
          schema:
            type: string
        - name: webAdeEnv
          in: path
          description: The ISSS WebADE environment
          required: true
          schema:
            type: string
            enum:
              - INT
              - TEST
              - PROD
      responses:
        '200':
          description: WebADE JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DependencyList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/webAde/{webAdeEnv}/preferences/insecurePrefs':
    get:
      summary: Returns a list of all WebADE applicationPreferences that have the sensitiveDataInd set to false matching the search criteria regular expression
      operationId: getInsecurePrefs
      tags:
        - Application Configuration
      parameters:
        - name: webAdeEnv
          in: path
          description: The ISSS WebADE environment
          required: true
          schema:
            type: string
            enum:
              - INT
              - TEST
              - PROD
        - name: searchCriteria
          in: query
          required: true
          schema:
            type: string
            example: secret
          description: A regular expression that will find preferences matching on their name
      responses:
        '200':
          description: WebADE JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsecurePrefList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/webAde/{webAdeEnv}/appConfigs/':
    get:
      summary: Returns WebADE JSON response for all acronyms
      operationId: appConfigGetAll
      tags:
        - Application Configuration
      parameters:
        - name: webAdeEnv
          in: path
          description: The ISSS WebADE environment
          required: true
          schema:
            type: string
            enum:
              - INT
              - TEST
              - PROD
      responses:
        '200':
          description: Array of WebADE JSONs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfigList'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /webade/appConfigForm:
    post:
      summary: Submit a proposed application
      operationId: appConfigFormPost
      tags:
        - Application Configuration
      requestBody:
        description: Form fields required to generate a minimal Application Configuration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppConfigForm'
      responses:
        '200':
          description: WebADE JSON response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppConfigResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /keyCloak/configForm:
    post:
      summary: Submit a proposed application to KeyCloak
      operationId: kcConfigFormPost
      tags:
        - KeyCloak Service Client Configuration
      requestBody:
        description: >-
          Form fields required to generate a minimal KeyCloak Service Client
          Configuration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KcConfigForm'
      responses:
        '200':
          description: Service Client Credentials and Endpoint information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KcConfigResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/Forbidden'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OpenID:
      type: openIdConnect
      openIdConnectUrl: 'https://example.com/.well-known/openid-configuration'
  schemas:
    AcronymDetail:
      type: object
      properties:
        acronym:
          type: string
          example: MSSC
        name:
          type: string
          example: Messaging Service Showcase
        permissionWebade:
          type: boolean
          example: true
        permissionWebadeNrosDms:
          type: boolean
          example: false
    AppConfig:
      type: object
      properties:
        '@type':
          type: string
          example: 'http://webade.gov.bc.ca/applicationConfiguration'
        applicationAcronym:
          type: string
          example: MSSC
        custodianNumber:
          type: integer
          minimum: 0
        applicationName:
          type: string
          example: Application Name
        applicationDescription:
          type: string
          example: Application Description
        applicationObjectPrefix:
          type: string
          example: null
        enabledInd:
          type: boolean
          example: true
        distributeTypeCd:
          type: string
          example: null
        managementEnabledInd:
          type: boolean
          example: false
        applicationVersion:
          type: string
          example: null
        reportedWebadeVersion:
          type: string
          example: null
        actions:
          type: array
          items:
            type: object
          example: []
        roles:
          type: array
          items:
            type: object
          example: []
        wdePreferences:
          type: array
          items:
            type: object
          example: []
        applicationPreferences:
          type: array
          items:
            type: object
          example: []
        globalPreferences:
          type: array
          items:
            type: object
          example: []
        defaultUserPreferences:
          type: array
          items:
            type: object
          example: []
        profiles:
          type: array
          items:
            type: object
          example: []
        serviceClients:
          type: array
          items:
            type: object
          example: []
        groupAuthorizations:
          type: array
          items:
            type: object
          example: []
    AppConfigForm:
      type: object
      required:
        - applicationAcronym
        - applicationName
        - applicationDescription
        - clientEnvironment
        - commonServices
        - passwordPublicKey
      properties:
        applicationAcronym:
          type: string
          example: MSSC
        applicationName:
          type: string
          example: Application Name
        applicationDescription:
          type: string
          example: Application Description
        commonServices:
          type: array
          items:
            type: string
            example: CMSG
          description: An array of applicationAcronyms
        passwordPublicKey:
          type: string
          description: A public key in PEM format without the headers
          example: MIGfMA0GCSqGS...
        clientEnvironment:
          type: string
          enum:
            - INT
            - TEST
            - PROD
          description: Which WebADE environment to work on
          example: INT
    AppConfigList:
      type: array
      items:
        $ref: '#/components/schemas/AppConfig'
      description: A list of Application Configurations
    AppConfigResponse:
      required:
        - webAdeResponse
        - generatedPassword
        - generatedServiceClient
      properties:
        webAdeResponse:
          $ref: '#/components/schemas/AppConfig'
        generatedPassword:
          type: string
          description: >-
            Contains the generated password, encrypted with the user-supplied
            public key
          example: ABC123XYZ
        generatedServiceClient:
          type: string
          description: Contains the service client name that was written to WebADE
          example: DOMO_SERVICE_CLIENT
    DependencyList:
      type: array
      items:
        $ref: '#/components/schemas/WebAdeProject'
      description: A list of dependent webade projects
    InsecurePrefList:
      type: array
      items:
        $ref: '#/components/schemas/WebAdePreferenceList'
      description: A list of webade projects and the list preference names
    EndpointStatus:
      type: object
      required:
        - name
        - endpoint
        - healthCheck
        - authenticated
        - authorized
      properties:
        name:
          type: string
          description: The name of the endpoint
          example: WebADE API
        endpoint:
          type: string
          description: Base endpoint URL
          example: 'https://example.com/v1/'
        healthCheck:
          type: boolean
          description: Is the endpoint reachable
        authenticated:
          type: boolean
          description: Are credentials valid to access endpoint
        authorized:
          type: boolean
          description: Do the credentials have the right permissions
    EndpointList:
      type: object
      required:
        - endpoints
      properties:
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/EndpointStatus'
          description: A list of Endpoint Statuses
    Error:
      required:
        - error
      properties:
        error:
          type: string
          description: contains a message about the failure
          example: Something errored
    KcConfigForm:
      type: object
      required:
        - applicationAcronym
        - applicationName
        - applicationDescription
        - commonServices
        - clientEnvironment
        - passwordPublicKey
      properties:
        applicationAcronym:
          type: string
          example: MSSC
        applicationName:
          type: string
          example: Application Name
        applicationDescription:
          type: string
          example: Application Description
        clientEnvironment:
          type: string
          enum:
            - DEV
            - TEST
            - PROD
          description: 'Which KeyCloak environment to work on - one of INT, TEST or PROD'
          example: INT
        commonServices:
          type: array
          items:
            type: string
            example: CHES
          description: An array of applicationAcronyms
        passwordPublicKey:
          type: string
          description: A public key in PEM format without the headers
          example: MIGfMA0GCSqGS...
    KcConfigResponse:
      required:
        - oidcTokenUrl
        - generatedPassword
        - generatedServiceClient
      properties:
        oidcTokenUrl:
          type: string
          description: >-
            Contains the OpenID Connect token url for the generated Service
            Client to get authenticated
          example: ABC123XYZ
        generatedPassword:
          type: string
          description: >-
            Contains the generated password, encrypted with the user-supplied
            public key
          example: ABC123XYZ
        generatedServiceClient:
          type: string
          description: Contains the service client name that was written to WebADE
          example: CHES_SERVICE_CLIENT
    WebAdeProject:
      type: object
      required:
        - applicationAcronym
        - applicationName
        - applicationDescription
        - enabled
      properties:
        applicationAcronym:
          type: string
          example: MSSC
        applicationName:
          type: string
          example: Application Name
        applicationDescription:
          type: string
          example: Application Description
        enabled:
          type: boolean
          example: true
      description: 'A WebADE project acronym, name, and description'
    WebAdePreferenceList:
      type: object
      required:
        - applicationAcronym
        - applicationName
        - applicationDescription
        - preferences
      properties:
        applicationAcronym:
          type: string
          example: MSSC
        applicationName:
          type: string
          example: Application Name
        applicationDescription:
          type: string
          example: Application Description
        preferences:
          type: array
          items:
            $ref: '#/components/schemas/WebadePreference'
      description: 'A WebADE project and a list of associated preferences'
    WebadePreference:
      type: object
      required:
        - dataTypeCode
        - description
        - name
        - sensitiveDataInd
        - setName
        - subTypeCode
        - value
      properties:
        dataTypeCode:
          type: string
          example: STRING
        description:
          type: string
          example: description of preference
        name:
          type: string
          example: posse.token.service.url
        sensitiveDataInd:
          type: boolean
          example: false
        setName:
          type: string
          example: aqua
        subTypeCode:
          type: string
          example: bootstrap-config
        value:
          type: string
          example: https://j200.gov.bc.ca/ws/NrsServices/session
      description: 'A WebADE preference object'
  responses:
    Forbidden:
      description: Lack required role to perform action
    NotFound:
      description: Not found
    UnauthorizedError:
      description: Access token is missing or invalid
